import { Link } from 'react-router-dom'
import SEOHead, { SITE_URL, SITE_NAME } from '../components/SEOHead'
import {
  PHONE_NUMBER,
  WHATSAPP_NUMBER,
  COMPANY_LEGAL_NAME,
  COMPANY_NUMBER,
  REGISTERED_OFFICE,
  SUPPORT_EMAIL,
} from '../lib/config'

interface Clause {
  heading: string
  paragraphs?: string[]
  list?: string[]
  subheading?: string
}

interface Section {
  number: number
  title: string
  clauses: Clause[]
}

const sections: Section[] = [
  {
    number: 1,
    title: 'Object and Acceptance',
    clauses: [
      {
        heading: '',
        paragraphs: [
          `These terms and conditions govern all sales conducted by ${COMPANY_LEGAL_NAME} and form an individual contract between us and our customers.`,
          'These terms and conditions take precedence over and supersede any prior agreements, contracts, commitments, declarations, promises, intentions, documentation, and information exchanged with the customer in relation to their order.',
          'A customer order is accepted as soon as the customer calls, messages, or otherwise contacts us and requests our emergency tyre services. The order is completed by reviewing the details thoroughly, including price and address, and correcting any errors that appear in the details before full acceptance is given.',
          'These terms and conditions are accessible through our website and may also be provided to the customer in a lasting format together with the acknowledgement of receipt.',
          'The contract is established as soon as the acknowledgement of receipt is generated by our company. The customer is notified once the contract is entered into, and it implies an obligation to pay the agreed price in favour of the company.',
        ],
      },
    ],
  },
  {
    number: 2,
    title: 'Products',
    clauses: [
      {
        heading: '',
        paragraphs: [
          `${COMPANY_LEGAL_NAME} is a provider of emergency mobile tyre fitting services across the UK, committed to delivering its services as quickly as possible after an order is placed and payment is taken. Response times vary depending on your location within the UK, traffic conditions, and any request for a specific brand or a mid-range or premium tyre.`,
          'Our products include budget tyres, mid-range tyres, and premium tyres. This information forms the contractual obligation of the seller that the customer agrees upon at the conclusion of the contract. Every contract is contingent upon the availability of the products.',
        ],
      },
    ],
  },
  {
    number: 3,
    title: 'Order',
    clauses: [
      {
        heading: '',
        subheading: '3.1 Access to the seller\'s website',
        paragraphs: [
          'Our website is public and can be accessed by all visitors throughout the year, seven days a week, twenty four hours a day. The website may occasionally be unavailable for maintenance, or because of technical errors. Any technical issues beyond our control may require additional time to restore access to the website.',
          'Our website is easy to navigate and use. You can place an order instantly by calling the number provided, by messaging us on WhatsApp, or by email, to receive an immediate response.',
        ],
      },
      {
        heading: '',
        subheading: '3.2 Professional reviews',
        paragraphs: [
          'The customer is invited to check the reviews on the website to get an idea of our services prior to placing an order.',
        ],
      },
      {
        heading: '',
        subheading: '3.3 Call, message, or email for the order',
        paragraphs: [
          `Once you call us on ${PHONE_NUMBER}, email us at ${SUPPORT_EMAIL}, or message us on WhatsApp at ${WHATSAPP_NUMBER}, your order will be processed after your confirmation. The order is confirmed and processed once payment is released. You will receive a confirmation from us shortly afterwards.`,
          'When you confirm your order you register with us by providing your (1) full name, (2) mobile number, (3) vehicle details such as make, model, and year, (4) exact tyre size, (5) number of tyres needed, (6) whether a wheel locking nut key is required, (7) postal code of your current vehicle location, (8) vehicle registration number, and (9) payment information. This information must be correct and accurate.',
          'We reserve the right to refuse access to our services or to change the eligibility criteria at our discretion. By registering, you affirm that you are of legal age to enter into a contract, or, if you register on behalf of a legal entity, that the entity is authorised to accept all liabilities associated with the contract.',
        ],
      },
      {
        heading: '',
        subheading: '3.4 Accurate information is required',
        paragraphs: [
          'You are solely responsible for providing us with accurate information, including your tyre size and postal code. Any inaccuracies may result in additional charges or a wasted journey, and we reserve the right to take appropriate action where information provided is knowingly false.',
          'You must inform us if you are missing your wheel locking nut key. Otherwise, we will assume that you possess it. In the event that our fitters need to remove or break the wheel locking nut in order to install the new tyre, an additional charge may be incurred.',
        ],
      },
      {
        heading: '',
        subheading: '3.5 Correct order',
        paragraphs: [
          'It is important for customers to specify their preferred type of product, whether they require a budget tyre, a mid-range tyre, or a premium tyre. If no preference is communicated, the seller will default to providing a budget or mid-range tyre.',
        ],
      },
      {
        heading: '',
        subheading: '3.6 Product type',
        paragraphs: [
          'Where a customer requests a specific brand or a premium tyre, this may affect both the price and the time required to source and fit the product. We will always confirm the price with you before any work begins.',
        ],
      },
      {
        heading: '',
        subheading: '3.7 Service timeframe',
        paragraphs: [
          'Our emergency tyre service is provided as promptly as possible after payment has been taken. The time required for services in remote areas away from major towns and cities may be longer. It may also be longer where the customer requests a specific brand or a premium range tyre that needs to be sourced.',
        ],
      },
      {
        heading: '',
        subheading: '3.8 Cancellation',
        paragraphs: [
          'After payment for our products and services, cancellation is only permissible within a five minute window. Once this timeframe has passed, cancellation is no longer possible. This cancellation policy is in place because we are an emergency mobile tyre fitting company and every cancellation carries a cost to us, including dispatching a fitter and reserving stock.',
        ],
      },
    ],
  },
  {
    number: 4,
    title: 'Financial Conditions',
    clauses: [
      {
        heading: '',
        paragraphs: [
          'We accept payment by card, PayPal, and bank transfer. Card payments are protected by a secure payment provider. Card information is never stored or retained for unauthorised use. Payment is secured with a 3D Secure protocol to protect sensitive data.',
          'Card payments are debited immediately and the action is irrevocable. By paying, customers authorise us to debit their card for the stated amount and confirm that they are the legal card holder. PayPal payments are also protected with a 3D Secure protocol. Payment by bank transfer is possible and is made to our registered bank account using the details provided. Customers should include their order number in the transfer reference for our records.',
        ],
      },
    ],
  },
  {
    number: 5,
    title: 'Ownership of the Product',
    clauses: [
      {
        heading: '',
        paragraphs: [
          'Upon validation of the order and completion of payment, the tyres become the sole property of the customer. All risk of loss or damage to the product passes to the customer once ownership has transferred, which happens as soon as payment has been taken and the product has been fitted or delivered.',
        ],
      },
    ],
  },
  {
    number: 6,
    title: 'Warranty',
    clauses: [
      {
        heading: '',
        paragraphs: [
          `At ${SITE_NAME} we stand behind the quality and performance of the tyres we fit, which come with the following warranty cover.`,
        ],
      },
      {
        heading: '',
        subheading: 'Warranty coverage',
        list: [
          'Limited treadwear warranty: if your tyre wears prematurely under normal driving conditions within the warranty period, we offer a replacement after a careful evaluation. This does not apply to damage caused by aggressive driving, potholes, or self-inflicted damage to the fitted tyres.',
          'Workmanship warranty: we stand behind our mobile tyre fitting service and provide error-free workmanship. If you find any fault with the fitting, you may contact us.',
        ],
      },
      {
        heading: '',
        subheading: 'Warranty exclusions',
        list: [
          'Damage resulting from neglect or misuse.',
          'Damage arising from the use of tyres for commercial purposes or racing.',
          'Cosmetic or sidewall damage that does not affect tyre performance.',
          'Tyres that are repaired or altered by unauthorised individuals.',
        ],
      },
      {
        heading: '',
        subheading: 'Claim process',
        paragraphs: [
          'To initiate a warranty claim, please present your original proof of service. Our fitters will promptly assess the tyre and process the claim. Where necessary, you may send the tyre to our address and we will evaluate it for faults. If the fault lies with us, your reasonable shipping and tyre costs will be reimbursed.',
        ],
      },
    ],
  },
  {
    number: 7,
    title: 'Limitation of Liability',
    clauses: [
      {
        heading: '',
        paragraphs: [
          'If one party does not fulfil its obligations under the contract, and unless its failure to perform is considered final, it will only be liable to pay damages if it was previously given notice to perform within a reasonable time. The party responsible may have to pay damages for failing to fulfil its duties or for delays, unless it can prove that something beyond its control prevented performance.',
          'Each party is only responsible for damages that were reasonably foreseeable when the contract was made, except in cases of gross negligence or fraud. Even then, liability is limited to the direct and immediate harm caused by the failure to fulfil the relevant obligation. Nothing in these terms limits or excludes liability where it would be unlawful to do so, including liability for death or personal injury caused by negligence.',
        ],
      },
    ],
  },
  {
    number: 8,
    title: 'Force Majeure',
    clauses: [
      {
        heading: '',
        paragraphs: [
          'If a force majeure event causes a permanent obstacle for one party, the contract ends automatically and both parties are released from their responsibilities.',
          'If a force majeure event causes a temporary obstacle, performance of the obligation is paused, unless the resulting delay is significant enough to justify terminating the contract.',
          'If a party cannot fulfil its contractual obligation due to force majeure, it is released from its responsibility to the extent that the obstacle is caused by force majeure and is permanent, unless it has agreed to bear the risk or had already been given notice to perform.',
        ],
      },
    ],
  },
]

export default function TermsConditions() {
  const schema = {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    name: 'Terms and Conditions',
    url: `${SITE_URL}/terms-and-conditions`,
    publisher: { '@type': 'Organization', name: SITE_NAME, url: SITE_URL },
  }

  return (
    <>
      <SEOHead
        title="Terms and Conditions"
        description={`The terms and conditions governing sales of tyres and mobile tyre fitting services by ${COMPANY_LEGAL_NAME}.`}
        schema={schema}
      />
      <section className="relative pt-24 pb-16 lg:pt-32 lg:pb-20 bg-white">
        <div className="mx-auto max-w-[800px] px-4 lg:px-6">
          <nav className="mb-6 flex items-center gap-2 text-xs text-[#6a6a6a]" style={{ fontFamily: 'JetBrains Mono' }}>
            <Link to="/" className="hover:text-[#d92a1d]">Home</Link><span>/</span><span className="text-[#1a1a1a]">Terms and Conditions</span>
          </nav>

          <h1 className="mb-4 text-3xl font-bold tracking-tight text-[#1a1a1a] sm:text-4xl" style={{ fontFamily: 'Space Grotesk' }}>
            Terms &amp; <span className="text-[#d92a1d]">Conditions</span>
          </h1>

          {/* Intro */}
          <div className="mb-8 space-y-4 text-base leading-relaxed text-[#6a6a6a]">
            <p>
              {COMPANY_LEGAL_NAME} is a UK-based company, registered at{' '}
              <a href="https://www.gov.uk/government/organisations/companies-house" target="_blank" rel="noopener noreferrer" className="font-semibold text-[#d92a1d] hover:text-[#b82418]">Companies House</a>{' '}
              under number {COMPANY_NUMBER}, providing emergency mobile tyre fitting throughout the UK through our website{' '}
              <a href={SITE_URL} className="font-semibold text-[#d92a1d] hover:text-[#b82418]">{SITE_URL.replace('https://', '')}</a>. We are registered under the Companies Act 2006 as a private limited company, with our registered office at {REGISTERED_OFFICE}.
            </p>
            <p>
              These general terms of sale are intended to govern all transactions involving the sale of products and services to any customer, whether a natural or legal person, and whether the customer is a professional or a non-professional individual (referred to as the customer), who has made a purchase through a call, email, or message. These terms and conditions aim to create a contractual framework between the customer and {COMPANY_LEGAL_NAME}.
            </p>
          </div>

          {/* Sections */}
          <div className="space-y-10">
            {sections.map((section) => (
              <div key={section.number}>
                <h2 className="mb-4 text-xl font-bold text-[#1a1a1a] sm:text-2xl" style={{ fontFamily: 'Space Grotesk' }}>
                  <span className="text-[#d92a1d]">{section.number}.</span> {section.title}
                </h2>
                <div className="space-y-5">
                  {section.clauses.map((clause, i) => (
                    <div key={i}>
                      {clause.subheading && (
                        <h3 className="mb-2 text-base font-semibold text-[#1a1a1a]" style={{ fontFamily: 'Space Grotesk' }}>{clause.subheading}</h3>
                      )}
                      {clause.paragraphs?.map((p, j) => (
                        <p key={j} className="mb-3 text-base leading-relaxed text-[#6a6a6a]">{p}</p>
                      ))}
                      {clause.list && (
                        <ul className="mb-3 space-y-2">
                          {clause.list.map((item, k) => (
                            <li key={k} className="flex gap-3 text-base leading-relaxed text-[#6a6a6a]">
                              <span className="mt-2 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-[#d92a1d]" />
                              <span>{item}</span>
                            </li>
                          ))}
                        </ul>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>

          {/* Contact */}
          <div className="mt-12 rounded-xl border border-gray-200 bg-gray-50 p-6">
            <h2 className="mb-2 text-lg font-bold text-[#1a1a1a]" style={{ fontFamily: 'Space Grotesk' }}>Questions about these terms?</h2>
            <p className="text-base leading-relaxed text-[#6a6a6a]">
              If you have any questions about these terms and conditions, please{' '}
              <Link to="/contact" className="font-semibold text-[#d92a1d] hover:text-[#b82418]">contact us</Link>{' '}
              or call {PHONE_NUMBER}.
            </p>
          </div>
        </div>
      </section>
    </>
  )
}
